### ISSUE TITLE
Ao criar ou editar uma noticia, quando coloca uma data/hora invalida, e depois uma válida, as vezes fica a borda vermelha

### ISSUE THREAD

**Issue by nicolastrres** [marighella/cms#21]
![screen shot 2014-10-17 at 6 20 09 pm](https://cloud.githubusercontent.com/assets/6579348/4686335/685aaf26-5644-11e4-9293-fdbe0a7e0115.png)
O problema é so visual porque ainda estando o borde vermelho, o cms permite postar a noticia.

**Comment by RatoX** [comment]
Issue antiga.

Fechando aqui.
