### ISSUE TITLE
Alertar ao usuario quando a organização seleccionada não possui skelleton

### ISSUE THREAD

**Issue by TaiseAssis** [marighella/cms#22]
Deixar na mesma tela e exibir a mensagem 'Atencão! Não é possível utilizar o Marighella para a opção selecionada. Selecione outra opção e tente novamente'

**Comment by RatoX** [comment]
Isso foi resolvido com o release https://github.com/marighella/cms/releases/tag/untagged-10e69efe7452b18e00c9
