### ISSUE TITLE
[Discussão] Integração File Service vulgo Image Service

### ISSUE THREAD

**Issue by gabrielcaires** [marighella/cms#32]
Imaginei uma forma de melhorar a dependência do image service, minha sugestão é a seguinte:

- Mudamos o repositório para marighella/file-service
- Colocamos um botão de deploy automatico para o heroku tipo esse:  [![Deploy](https://www.herokucdn.com/deploy/button.png)](https://heroku.com/deploy?template=https://github.com/heroku/node-js-sample) mais informações em https://devcenter.heroku.com/articles/heroku-button
- Ao instalar a aplicação exibimos um formulário onde pedimos os dados necessários para integração com cada plataforma (Drive, Flickr e outros)
- Criamos um arquivo de configuração (ou usamos o skelleton) que fica no repositório do blog da pessoa, com o link para o novo serviço

**Comment by mauriciomelo** [comment]
Duplicado #42
