### ISSUE TITLE
Criar posts relacionados usando as tags que o usuario colocou.

### ISSUE THREAD

**Issue by RatoX** [marighella/cms#39]
Atualmente os posts relacionados são de responsabilidade do Jekyll, nós queremos acabar com isso e trazer essa responsabilidade para o Marighella, fazendo esses pontos aqui:

- [x] 1. Criar um algoritmo de tag-frequencia para o Marighella. SHA: b8a1d3a
- [x] 2. Aproveitar as tags existentes para fazer um serviço de autocompletar. SHA: 8ff425634252a38cdd98a762dc24ba2c6ac9af26 
- [ ] 3. Utilizar de forma parametrizada o endereço para o arquivo **novo.mst.org.br/tags.json**
- [x] 4. Colocar as 6 postagens mais relevantes no markdown
- [x] 5. Exibir ao usuário as nóticias escolhidas pelo algoritmo.
- [x] 6. Permitir que o usuário diga quais as postagens que ele quer como relacionadas, utilizando primeiramente um filtro das tags.

**Comment by RatoX** [comment]
Já preenchemos o markdown com a informação nova.

**Comment by RatoX** [comment]
Os pontos 1 e 2 já estão em homologação no merge.

Criamos um outro branch para terminar o trabalho: 
https://github.com/marighella/cms/tree/card_39

**Comment by TaiseAssis** [comment]
Um post é sugerido somente após inclusão da segunda tag relacionada a outro post. Esta correto?
