### ISSUE TITLE
Criar estrategia para upload de imagens e pdf para serviços como o Flickr e Google Drive. 

### ISSUE THREAD

**Issue by RatoX** [marighella/cms#42]
Atualmente utilizamos um serviço externo chamado **mst-image-service** para salvar os arquivos no flickr/drive dos movimentos sociais, porém é um serviço de difícil replicação para novos movimentos, precisamos banir esse serviço, para isso precisamos discutir sobre:

- Melhor estrategia para que um usuário/organização use sua conta para logar nos serviços externos;
- Como todos os jornalistas teriam acesso a mesma conta do movimento social sem digitar as credenciais do movimento social

Vai estar pronto quando:

1. Usuários   
1.2 Possam autenticar-se no serviço do Flickr   
1.3 Não precisem se autenticar mais de uma vez para a mesma sessão   
1.4 Possam subir imagens direto pro Flickr

**Comment by RatoX** [comment]
Começamos os trabalhos aqui:

SHA: 892fc3bdf8ca175724cd13c568e772c981c5868f

**Comment by RatoX** [comment]
Estamos testando a opção de autenticar no flickr da pessoa utilizando o OAuth.io.

**Comment by ludug3r0** [comment]
## Etapas para o primeiro spike (autenticacao no flickr):
- [ ] Autenticar usuario no flickr
  - [ ] Adicionar botao de autenticacao do flickr na tela de criacao de noticias acima da galeria
  - [ ] Autenticar tanto usando oauth.io quanto api do flickr e mensurar dificuldades de implementacao
- [ ] Salvar dados da autenticacao localmente
  - [ ] Pesquisar como sites permanecem logados de forma segura utilizando apenas front end
  - [ ] Verificar quais bibliotecas que poderiam criptografar (se necessario) estes dados localmente e quais limitacoes de browsers
