### ISSUE TITLE
Ao escolher um mes que não tem posts

### ISSUE THREAD

**Issue by nicolastrres** [marighella/cms#46]
Ao escolher um mes que não tem posts gera um erro e permanecem os posts antes pesquisados pelo usuario. 

Passos para reproduzir o erro: 
1.  Ir a um mes sem posts.
2.  Filtrar os posts por outro mes que tem posts.
3.  Voltar ao mes sem posts.
4.  Os posts do mes com posts ainda aparecem.

**Comment by RatoX** [comment]
Problema resolvido com a implementação do novo sistema de pesquisa. #41
