### ISSUE TITLE
Alterar a forma de autenticação dos serviços para upload de imagens.

### ISSUE THREAD

**Issue by pereiragislene** [marighella/cms#50]
Cada organização deve ter autonomia para informar a respectiva conta do flickr utilizada para armazenar as imagens utilizadas nos posts. 

1 -A  organização não possui credenciais
Dado uma organização sem credenciais do flickr 
quando o jornalista adicionar uma imagem
então devemos solicitar usuário e senha do flickr e armazenar esta autenticação para futuras postagens.

2 - Organização possui credenciais
Dado que uma organização que possui credenciais no Flickr armazenada
quando um jornalista adicionar uma imagem
então devemos utilizar a credencial conhecida para autenticar no Flickr.

**Comment by pereiragislene** [comment]
Confirmar com o cliente se quem vai postar as notícias tem acesso à conta do Flickr da instituição.

**Comment by RatoX** [comment]
Duplicada ?

Coloca o link da original

**Comment by TaiseAssis** [comment]
https://github.com/marighella/cms/issues/42
