### ISSUE TITLE
Refatorar testes End-to-end

### ISSUE THREAD

**Issue by willmendesneto** [marighella/cms#52]
Refatorar os testes end-to-end no CMS:

- Page Objects com muitas responsabilidades;
- Remover `.sleep()` e `.wait()` desnecessários;

**Comment by RatoX** [comment]
Os sleeps e os wait podemos trocar por promessas?

**Comment by willmendesneto** [comment]
Sim, sim. Os eventos `.click()` do protractor, por exemplo, estão retornando promises. Os que já não estiverem podemos utilizar o promise. Cola comigo @RatoX ?

**Comment by RatoX** [comment]
Pode ser quinta de tarde?
