### ISSUE TITLE
Listagem não atualiza depois de edição

### ISSUE THREAD

**Issue by RatoX** [marighella/cms#59]
O resultado da tela da pesquisa não atualiza depois que modificamos qualquer postagem.

Reprodução:

1. Escolha uma postagem legal:

![screen shot 2015-01-28 at 11 15 42 am](https://cloud.githubusercontent.com/assets/3452187/5939050/24551d98-a6df-11e4-836a-95a6ad9132b3.png)

2. Altere o titulo para algo muito foda:
![screen shot 2015-01-28 at 11 16 06 am](https://cloud.githubusercontent.com/assets/3452187/5939053/2a25b462-a6df-11e4-888b-9e83e44bdcfa.png)

3. Fique triste:

![screen shot 2015-01-28 at 11 16 18 am](https://cloud.githubusercontent.com/assets/3452187/5939055/30507728-a6df-11e4-8c6f-16ebe293aab3.png)

**Comment by willmendesneto** [comment]
Isso acontece porque o objeto de listagem não é atualizado. Você pode fazer isso por 2 formas:

- Atualizar a lista de objetos por completo quando editar;
- Verificar a resposta da atualização na API e se tudo estiver ok, atualizar o item no objeto de posts;

**Comment by RatoX** [comment]
@willmendesneto  como assim?

Quando rodamos o:
```javascript
$location.path('/post/search'); 
```

Ele não deveria recarregar meu controle?

**Comment by mauriciomelo** [comment]
Problema está na API do github, quando é postada a notícia demora um tempo até ela ficar disponível para pesquisa.

**Comment by willmendesneto** [comment]
@RatoX , ela não recarrega o controller (vide https://docs.angularjs.org/api/ng/service/$location).
