### ISSUE TITLE
Remover o CKEDitor e colocar algo mais leve.

### ISSUE THREAD

**Issue by RatoX** [marighella/cms#61]
Sério, sáporra é muito pesada para conexões baixas

**Comment by willmendesneto** [comment]
@RatoX , estão rodando as tarefas de minificação e concatenação dos arquivos e mesmo assim está pesado? 

Qual o tamanho dos arquivos finais? Talvez seja uma boa separar em requisições menores, a depender.

**Comment by RatoX** [comment]
Estão sim, mas o CKEditor tem muita coisa para carregar.
