### ISSUE TITLE
Permitir configurar o 'pirulito'

### ISSUE THREAD

**Issue by TaiseAssis** [marighella/cms#70]
Atualmente para editar o pirulito é necessário atualizar um arquivo de configuração do site, entretanto essa é uma parte muito mais relacionada com o conteúdo (responsabilidade do editor/jornalista) do que a com configuração (responsabilidade do dev)

**Comment by willmendesneto** [comment]
@TaiseAssis o que é o pirulito?

**Comment by mauriciomelo** [comment]
@willmendesneto  se você acessar a home do http://www.mst.org.br/  verá algo como "**novidade!** Você já viu a nova página do **Nossa Produção** ?", isso chamamos de pirulito (Por quê? Também tenho curiosidade).
