### ISSUE TITLE
[Musicoteca] - Ordernar musicas

### ISSUE THREAD

**Issue by RatoX** [marighella/cms#76]
Para que seja possível escutar as músicas em uma ordem predeterminada devemos permitir ordenar as músicas ao adicioná-las nos álbuns.

## Critérios
- Alterar a ordem de qualquer faixa adicionada.

**Comment by TaiseAssis** [comment]
A ordenacao confunde o usuario pois a seta junto ao numero da a sensacao de q ao clicar eu mudo de ordem
